Add RAG search query generation option
cohere-ai/cohere-developer-experience pull request #135
Opened 2024-09-17 14:49 UTC by mrmer1

Two options for RAG search query generation:
- search_queries_only param
- tools

2024-09-17 15:11 UTC, maximevoisincohere requested changes
LGTM. Maybe we could add another example that says: you can then customize the tool preamble and/or the tool definition, to generate queries that are more relevant to your use case. 

For example, [[ we do the verbose example from this notebook: https://colab.research.google.com/drive/1oHg6lO-VnXWRFQV5WLLRy6u_SE--jrpG#scrollTo=EeHkg9zet7v5 ]] and show that it generates more queries than before?

2024-09-17 15:11 UTC, maximevoisincohere commented on fern/pages/text-generation/retrieval-augmented-generation-rag.mdx
> +##### Option 2: Using a tool use approach
maybe "Option 2: Using a Tool"?

2024-09-17 15:11 UTC, maximevoisincohere commented on fern/pages/text-generation/retrieval-augmented-generation-rag.mdx
> +If you are looking for greater control over how search queries are generated, you can use the tool use approach to generate search queries.
you can use Cohere's Tools capabilities to generate search queries

2024-09-18 01:55 UTC, mrmer1 reviewed
done

2024-09-18 14:31 UTC, billytrend-cohere approved these changes

2024-09-20 17:36 UTC, trentfowlercohere approved these changes
Looks good to me!

2024-09-23 12:51 UTC, lfayoux approved these changes

2024-09-23 16:50 UTC, merged